version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-management-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - translation-network

  nginx:
    image: nginx:alpine
    container_name: translation-management-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - translation-network

  db:
    image: mysql:8.0
    container_name: translation-management-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: translation_management
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: 
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - translation-network

volumes:
  dbdata:
    driver: local

networks:
  translation-network:
    driver: bridge